"""Native video-VAE audit of the real frozen low-sampler A/B/A source outputs.

The saved B suffix was *generated by the low H3 model*, unlike the earlier
decoder-only prefix experiment. Both clean videos are decoded on matching full
native timelines and measured with the same static background ROIs.
"""
from __future__ import annotations

import hashlib
import json
import os
import tempfile
from pathlib import Path

import torch

from .local_boundary_audit import (
    _AUDIT_MODEL_OWNERS,
    geometry_comparison,
    normalize_bundle_path,
    read_verified_operand,
)
from .native_prefix_counterfactual import _native_pixels, _temporal_increment, _variant_pixels
from .partitioned_stage import tensor_sha256
from .stage_static_roi_audit import PROFILES, compare_same_frame_prefix_rois, parse_static_rois

POLICY = "h3_frozen_low_source_aba_native_decode_v1"
KIND = "h3_flow_frozen_low_source_aba_v1"
NAMES = (
    "source_A_full",
    "source_B_full",
    "source_A_replay_full",
    "authoritative_target_prefix",
    "first_actual_A",
    "first_actual_B",
    "first_actual_A_replay",
)


def audit_saved_low_aba(
    vae,
    bundle_path,
    join_frame,
    process_out,
    *,
    static_roi_profile="01784_room",
    static_roi_json="",
    feature_tracking_enabled=True,
    expected_manifest_sha256=None,
):
    if type(join_frame) is not int or join_frame < 10:
        raise ValueError("a valid assembled join frame is required")
    native = getattr(vae, "first_stage_model", None)
    expected = {"tokens_chunk_size": 5, "token_overlap": 2, "frame_pre_padding": 3, "clip_length": 17}
    if native is None or any(getattr(native, key, None) != value for key, value in expected.items()):
        raise ValueError("connect the production native MiniMax H3 video VAE")
    rois = parse_static_rois(static_roi_profile, static_roi_json)
    if not rois:
        raise ValueError("saved low A/B requires named background regions")
    directory = Path(
        normalize_bundle_path(bundle_path, platform=os.name, wsl_distro=os.environ.get("WSL_DISTRO_NAME"))
    ).expanduser().resolve()
    if directory.name == "manifest.json":
        directory = directory.parent
    raw = (directory / "manifest.json").read_bytes()
    digest = hashlib.sha256(raw).hexdigest()
    if expected_manifest_sha256 and digest != expected_manifest_sha256:
        raise ValueError("frozen low A/B manifest hash does not match selected witness")
    manifest = json.loads(raw)
    if manifest.get("schema") != 1 or manifest.get("kind") != KIND:
        raise ValueError("expected the exact frozen low-source A/B/A export manifest")
    metadata = manifest.get("metadata", {})
    if (
        metadata.get("policy") != "h3_frozen_low_source_aba_v1"
        or metadata.get("model_domain") != "model_internal_clean"
    ):
        raise ValueError("frozen source A/B operands have an unknown model domain or policy")
    if not isinstance(metadata.get("low_input_pairing"), dict) or not metadata["low_input_pairing"].get(
        "input_pair_eligible"
    ):
        raise ValueError("A/B witness was not recorded from hash-matched low-stage inputs")
    if metadata.get("reproduction_verified") is not True:
        raise ValueError("frozen low A' did not reproduce A; decoder audit is unqualified")
    hashes = {}
    tensors = {name: read_verified_operand(directory, manifest["tensor_bytes"], name, hashes) for name in NAMES}
    a, b, a2, target, first_a, first_b, first_a2 = (tensors[name] for name in NAMES)
    prefix_t = metadata["prefix_t"]
    temporal = metadata["temporal"]
    source_hw = tuple(metadata["source_hw"])
    target_hw = tuple(metadata["target_hw"])
    if (
        type(prefix_t) is not int
        or prefix_t < 7
        or (prefix_t - 2) % 5
        or type(temporal) is not int
        or temporal <= prefix_t
        or (temporal - 2) % 5
        or a.shape != b.shape
        or a.shape != a2.shape
        or a.shape != (1, 24, temporal, *source_hw)
        or target.shape != (1, 24, prefix_t, *target_hw)
        or first_a.shape != first_b.shape
        or first_a.shape != first_a2.shape
        or first_a.shape != a.shape
        or any(t.dtype != torch.float32 or t.device.type != "cpu" for t in tensors.values())
    ):
        raise ValueError("saved low A/B/A source/first-prediction temporal or spatial geometry changed")
    for original, repeated, start in ((a, a2, prefix_t), (first_a, first_a2, 0)):
        if (original[:, :, start:] - repeated[:, :, start:]).abs().max() > 1e-5:
            raise ValueError("replayed A no longer matches saved first/source output within 1e-5")
    output_sha_before = {name: hashes[name] for name in NAMES}
    origin = join_frame - prefix_t // 5 * 17 - 5
    labels = list(range(join_frame - 5, join_frame + 21))
    pixels_a, elapsed_a = _native_pixels(vae, a, process_out, origin, labels)
    pixels_b, elapsed_b = _native_pixels(vae, b, process_out, origin, labels)
    full_rois = {**rois, "upper45_full": (0.0, 0.0, 1.0, 0.45)}
    same = compare_same_frame_prefix_rois(pixels_a, pixels_b, labels, rois=full_rois)
    if any(tensor_sha256(tensors[name]) != hashes[name] for name in NAMES):
        raise RuntimeError("saved low A/B operand changed during read-only decode")
    return {
        "policy": POLICY,
        "input_manifest_sha256": digest,
        "input_tensor_sha256": output_sha_before,
        "model_domain": "model_internal_clean",
        "source_policy_A": "native_source_carry_v1",
        "source_policy_B": "half_pixel_latent_v1",
        "native_source_temporal": temporal,
        "prefix_t": prefix_t,
        "original_target_prefix_sha256": hashes["authoritative_target_prefix"],
        "join_frame": join_frame,
        "frame_labels": labels,
        "source_canvas_px": [source_hw[0] * 16, source_hw[1] * 16],
        "source_generation_suffix_is_altered": not torch.equal(a[:, :, prefix_t:], b[:, :, prefix_t:]),
        "a_replay_verified": True,
        "baseline_A": _variant_pixels(pixels_a, labels, join_frame, rois, feature_tracking_enabled),
        "candidate_B": _variant_pixels(pixels_b, labels, join_frame, rois, feature_tracking_enabled),
        "same_frame_A_to_B": same,
        "same_frame_geometry": geometry_comparison(pixels_a, pixels_b, labels),
        "temporal_increment_delta": _temporal_increment(pixels_a, pixels_b, labels),
        "decode": {
            "vae_class": f"{type(native).__module__}.{type(native).__qualname__}",
            "full_source_vae_calls": 2,
            "extra_h3_nfe": 0,
            "A_ms": elapsed_a,
            "B_ms": elapsed_b,
        },
        "limitations": [
            "A/B differs in the generated latent suffix; this is a real low-model intervention, not decoder-only.",
            "f174 anchor photometry and sharpness may differ across A/B; compare same-frame absolute gradients.",
            "Background trackers independently pick features per variant, not necessarily identical landmarks.",
            "An A-to-A' replay pass bounds observable state carryover, not all hidden model/attention caches.",
            "Source-grid low-model effects are not rendered target-high acceptance or audio acceptance.",
        ],
        "output_modified": False,
        "rendered_accepted": False,
    }


class H3FrozenLowABAudit:
    @classmethod
    def INPUT_TYPES(cls):
        return {
            "required": {
                "video_vae": ("VAE",),
                "bundle_path": ("STRING", {"default": ""}),
                "chunk_join_frame": ("INT", {"default": 175, "min": 10, "max": 10000000}),
            },
            "optional": {
                "static_roi_profile": (list(PROFILES), {"default": "01784_room"}),
                "static_roi_json": ("STRING", {"default": "", "multiline": True}),
                "feature_tracking_enabled": ("BOOLEAN", {"default": True}),
                "expected_manifest_sha256": ("STRING", {"default": ""}),
            },
        }

    RETURN_TYPES = ("STRING",)
    RETURN_NAMES = ("numerical_report",)
    FUNCTION = "audit"
    CATEGORY = "MiniMax H3/diagnostics"
    OUTPUT_NODE = True
    DESCRIPTION = "Read-only native VAE analysis of actual frozen low-sampler A/B/A generated suffixes."

    @classmethod
    def IS_CHANGED(cls, **_kwargs):
        _AUDIT_MODEL_OWNERS.retain()
        return float("nan")

    def audit(
        self,
        video_vae,
        bundle_path,
        chunk_join_frame,
        static_roi_profile="01784_room",
        static_roi_json="",
        feature_tracking_enabled=True,
        expected_manifest_sha256="",
    ):
        _AUDIT_MODEL_OWNERS.retain()
        import folder_paths
        from comfy.latent_formats import MiniMaxH3Video

        result = audit_saved_low_aba(
            video_vae,
            bundle_path,
            chunk_join_frame,
            MiniMaxH3Video().process_out,
            static_roi_profile=static_roi_profile,
            static_roi_json=static_roi_json,
            feature_tracking_enabled=feature_tracking_enabled,
            expected_manifest_sha256=expected_manifest_sha256 or None,
        )
        serialized = json.dumps(result, indent=2, allow_nan=False)
        directory = Path(folder_paths.get_output_directory()) / "h3_flow_regenerate" / "boundary_audits"
        directory.mkdir(parents=True, exist_ok=True)
        with tempfile.NamedTemporaryFile(
            mode="w",
            encoding="utf-8",
            prefix="frozen-low-aba-",
            suffix=".json",
            dir=directory,
            delete=False,
        ) as stream:
            stream.write(serialized + "\n")
        return {"ui": {"text": [serialized, f"Numerical report: {Path(stream.name).name}"]}, "result": (serialized,)}


NODE_CLASS_MAPPINGS = {"H3FrozenLowABAudit": H3FrozenLowABAudit}
NODE_DISPLAY_NAME_MAPPINGS = {"H3FrozenLowABAudit": "MiniMax H3 Frozen Low A/B Audit"}
